### ISSUE TITLE
pkg安装报错

### ISSUE THREAD

**Issue by codeway3** [biezhi/runcat_pyside#1]
macOS 10.15.7
python 3.9.5

python run_cat.py 正常

打包后点击 pkg 文件安装报错
报错信息为：未能完成该操作。（com.apple.installer.pagecontroller错误-1。）

尝试打包成 dmg 运行或直接解压 pkg 均未能成功。

**Comment by hellokaton** [comment]
@codeway3 使用 `pyinstaller` 打包后的结果是 `.app` 文件，打包命令:

```bash
pyinstaller --clean -Fw -i runcat.ico --add-data "resources:./resources" run_cat.py
```

**Comment by codeway3** [comment]
.pkg原来是中间文件吗，没看到dist下的.app。
感谢，问题已解决。
